version: '3'

services:
  nginx:
    image: nginx:stable-alpine3.17-slim
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend_blue
      - backend_green
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  backend_blue:
    container_name: backend_blue
    image: backend:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend_blue:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3


  backend_green:
    container_name: backend_green
    image: backend:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend_blue:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
