name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          echo "$DOCKER_USERNAME"
          echo "${{env.DOCKER_USERNAME}}"
          # docker build -t backend .
          # docker tag backend:latest $DOCKER_USERNAME/backend-${{ github.sha }}
          # docker push $DOCKER_USERNAME/backend-${{ github.sha }}
          # docker tag $DOCKER_USERNAME/backend-${{ github.sha }} backend:latest
          # docker push $DOCKER_USERNAME/backend:latest
